- name: Disable Old Version
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable New Version
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Install the latest version of Nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Copy Backend Service File
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Add Application user
  ansible.builtin.user:
    name: expense

- name: Import Role
  ansible.builtin.import_role:
    name: common
    tasks_from: app_prereq

- name: Download Dependencies
  community.general.npm:
    path: /app

- name: Install New relic npm dependency
  ansible.builtin.shell: npm install newrelic --save
  args:
    chdir: /app

- name: Install Mysql
  ansible.builtin.dnf:
    name: mysql

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql-dev.akrdevops.online -uroot -pExpenseApp@1 < /app/schema/backend.sql

- name: Start service nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
