- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Copy expense conf
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import Role
  ansible.builtin.import_role:
    name: common
    tasks_from: app_prereq

- name: Start service nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: New Relic Setup for Nginx
  ansible.builtin.shell: curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash && sudo NEW_RELIC_API_KEY={{ lookup('amazon.aws.aws_ssm', 'expense.newrelic.key', region='us-east-1' ) }} NEW_RELIC_ACCOUNT_ID={{ lookup('amazon.aws.aws_ssm', 'newrelic.account.id', region='us-east-1' ) }} /usr/local/bin/newrelic install -y
