- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Copy expense conf
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import Role
  ansible.builtin.import_role:
    name: common
    tasks_from: app_prereq

- name: Start service nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes
    daemon-reload: yes

