- name: Remove App Directory
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: absent

- name: Create App Directory
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: directory
    owner: "{{app_user}}"

- name: Unarchive file
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/{{component_name}}.zip
    dest: "{{ app_path }}"
    remote_src: yes

- name: Copy Elastic Repo
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install Filebeat
  ansible.builtin.dnf:
    name: filebeat
    state: installed

- name: Copy Filebeat File
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: Start Filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted

